import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'pet_001',
      name: 'Buddy',
      type: 'dog',
      breed: 'Golden Retriever',
      tenantName: 'James Cooper',
      tenantUnit: 'Unit 8A',
      property: 'Sunset Towers',
      weight: 72,
      weightUnit: 'lbs',
      approvalStatus: 'approved',
      vaccinationStatus: 'up_to_date',
      registrationDate: '2025-06-15T00:00:00Z',
      licenseNumber: 'PET-2025-0412',
      notes: 'Certified emotional support animal. Documentation on file.',
    },
    {
      id: 'pet_002',
      name: 'Whiskers',
      type: 'cat',
      breed: 'British Shorthair',
      tenantName: 'Maria Santos',
      tenantUnit: 'Unit 3C',
      property: 'Harbor View Apartments',
      weight: 11,
      weightUnit: 'lbs',
      approvalStatus: 'approved',
      vaccinationStatus: 'up_to_date',
      registrationDate: '2025-09-01T00:00:00Z',
      licenseNumber: 'PET-2025-0723',
      notes: 'Indoor cat only. No balcony access.',
    },
    {
      id: 'pet_003',
      name: 'Rocky',
      type: 'dog',
      breed: 'German Shepherd',
      tenantName: 'Priya Sharma',
      tenantUnit: 'Unit 14C',
      property: 'Harbor View Apartments',
      weight: 85,
      weightUnit: 'lbs',
      approvalStatus: 'pending',
      vaccinationStatus: 'up_to_date',
      registrationDate: '2026-03-01T00:00:00Z',
      licenseNumber: 'PET-2026-0089',
      notes: 'Breed review required per pet policy. Awaiting board approval.',
    },
    {
      id: 'pet_004',
      name: 'Luna',
      type: 'cat',
      breed: 'Siamese',
      tenantName: 'Sophie Laurent',
      tenantUnit: 'Unit 11A',
      property: 'Riverside Lofts',
      weight: 9,
      weightUnit: 'lbs',
      approvalStatus: 'approved',
      vaccinationStatus: 'missing',
      registrationDate: '2026-01-20T00:00:00Z',
      licenseNumber: 'PET-2026-0015',
      notes: 'Rabies vaccination overdue — notice sent to tenant. Deadline: March 15.',
    },
    {
      id: 'pet_005',
      name: 'Charlie',
      type: 'dog',
      breed: 'Beagle',
      tenantName: 'Anna Williams',
      tenantUnit: 'Unit 6B',
      property: 'Riverside Lofts',
      weight: 28,
      weightUnit: 'lbs',
      approvalStatus: 'approved',
      vaccinationStatus: 'up_to_date',
      registrationDate: '2025-04-10T00:00:00Z',
      licenseNumber: 'PET-2025-0298',
      notes: 'No issues. Annual renewal due April 2026.',
    },
    {
      id: 'pet_006',
      name: 'Nibbles',
      type: 'other',
      breed: 'Holland Lop Rabbit',
      tenantName: 'Lisa Park',
      tenantUnit: 'Unit 15D',
      property: 'Cedar Park Villas',
      weight: 4,
      weightUnit: 'lbs',
      approvalStatus: 'approved',
      vaccinationStatus: 'up_to_date',
      registrationDate: '2025-11-05T00:00:00Z',
      licenseNumber: 'PET-2025-0934',
      notes: 'Small pet — cage required in common areas. Approved under exotic pet policy.',
    },
  ]

  return NextResponse.json({ data })
}
