import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'mki_001',
      address: '1247 Sunset Blvd, Unit 8A',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      property: 'Sunset Towers',
      price: 3200,
      pricePerSqft: 4.27,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 750,
      listingStatus: 'active',
      daysOnMarket: 5,
      source: 'Zillow',
      sourceUrl: 'https://zillow.com/example1',
      comparables: 8,
      lastUpdated: '2026-03-03T00:00:00Z',
    },
    {
      id: 'mki_002',
      address: '589 Maple Avenue, Unit 3B',
      city: 'Portland',
      state: 'OR',
      zipCode: '97201',
      property: 'Maple Grove Residences',
      price: 2150,
      pricePerSqft: 2.87,
      bedrooms: 1,
      bathrooms: 1,
      sqft: 750,
      listingStatus: 'active',
      daysOnMarket: 12,
      source: 'Redfin',
      sourceUrl: 'https://redfin.com/example2',
      comparables: 12,
      lastUpdated: '2026-03-02T00:00:00Z',
    },
    {
      id: 'mki_003',
      address: '2200 Harbor Drive, Unit 15D',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      property: 'Harbor View Apartments',
      price: 3850,
      pricePerSqft: 3.85,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1000,
      listingStatus: 'pending',
      daysOnMarket: 21,
      source: 'MLS',
      sourceUrl: 'https://mls.example.com/listing3',
      comparables: 6,
      lastUpdated: '2026-03-01T00:00:00Z',
    },
    {
      id: 'mki_004',
      address: '445 Oakwood Lane, Unit 7C',
      city: 'Denver',
      state: 'CO',
      zipCode: '80202',
      property: 'Oakwood Estates',
      price: 2680,
      pricePerSqft: 3.12,
      bedrooms: 2,
      bathrooms: 1,
      sqft: 860,
      listingStatus: 'active',
      daysOnMarket: 8,
      source: 'Zillow',
      sourceUrl: 'https://zillow.com/example4',
      comparables: 15,
      lastUpdated: '2026-03-03T00:00:00Z',
    },
    {
      id: 'mki_005',
      address: '78 Riverside Way, Unit 2A',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      property: 'Riverside Lofts',
      price: 1950,
      pricePerSqft: 2.60,
      bedrooms: 1,
      bathrooms: 1,
      sqft: 750,
      listingStatus: 'rented',
      daysOnMarket: 0,
      source: 'Redfin',
      sourceUrl: 'https://redfin.com/example5',
      comparables: 10,
      lastUpdated: '2026-02-28T00:00:00Z',
    },
    {
      id: 'mki_006',
      address: '912 Cedar Park Circle, Unit 11B',
      city: 'Nashville',
      state: 'TN',
      zipCode: '37203',
      property: 'Cedar Park Villas',
      price: 2450,
      pricePerSqft: 3.06,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 800,
      listingStatus: 'active',
      daysOnMarket: 14,
      source: 'MLS',
      sourceUrl: 'https://mls.example.com/listing6',
      comparables: 9,
      lastUpdated: '2026-03-02T00:00:00Z',
    },
  ]

  return NextResponse.json({ data })
}
