import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'vis_001',
      name: 'Sarah Mitchell',
      email: 'sarah.mitchell@email.com',
      phone: '+1 (415) 555-0142',
      host: 'James Cooper',
      hostUnit: 'Unit 8A',
      property: 'Sunset Towers',
      purpose: 'Personal Visit',
      checkInTime: '2026-03-03T09:15:00Z',
      checkOutTime: null,
      status: 'checked_in',
      visitorType: 'guest',
      notes: 'Bringing small dog, approved by host',
    },
    {
      id: 'vis_002',
      name: 'David Chen',
      email: 'david.chen@hvac-pro.com',
      phone: '+1 (415) 555-0198',
      host: 'Property Management',
      hostUnit: 'Maintenance Office',
      property: 'Maple Grove Residences',
      purpose: 'HVAC Inspection',
      checkInTime: '2026-03-03T10:30:00Z',
      checkOutTime: '2026-03-03T12:45:00Z',
      status: 'checked_out',
      visitorType: 'contractor',
      notes: 'Annual HVAC system inspection for Building B',
    },
    {
      id: 'vis_003',
      name: 'Emily Rodriguez',
      email: 'emily.r@email.com',
      phone: '+1 (415) 555-0267',
      host: 'Maria Santos',
      hostUnit: 'Unit 3C',
      property: 'Harbor View Apartments',
      purpose: 'Apartment Tour',
      checkInTime: null,
      checkOutTime: null,
      status: 'pending',
      visitorType: 'prospective_tenant',
      notes: 'Interested in 2BR unit, pre-qualified',
    },
    {
      id: 'vis_004',
      name: 'Robert Thompson',
      email: 'r.thompson@deliveries.com',
      phone: '+1 (415) 555-0334',
      host: 'Front Desk',
      hostUnit: 'Lobby',
      property: 'Oakwood Estates',
      purpose: 'Package Delivery',
      checkInTime: '2026-03-03T14:20:00Z',
      checkOutTime: null,
      status: 'checked_in',
      visitorType: 'delivery',
      notes: 'Fragile items — handle with care',
    },
    {
      id: 'vis_005',
      name: 'Angela Foster',
      email: 'angela.foster@lawfirm.com',
      phone: '+1 (415) 555-0411',
      host: 'Property Management',
      hostUnit: 'Leasing Office',
      property: 'Riverside Lofts',
      purpose: 'Lease Consultation',
      checkInTime: null,
      checkOutTime: null,
      status: 'pending',
      visitorType: 'professional',
      notes: 'Representing tenant in lease renewal negotiation',
    },
    {
      id: 'vis_006',
      name: 'Michael Park',
      email: 'm.park@email.com',
      phone: '+1 (415) 555-0189',
      host: 'Lisa Park',
      hostUnit: 'Unit 15D',
      property: 'Cedar Park Villas',
      purpose: 'Personal Visit',
      checkInTime: '2026-03-03T08:00:00Z',
      checkOutTime: '2026-03-03T10:30:00Z',
      status: 'checked_out',
      visitorType: 'guest',
      notes: 'Family member — frequent visitor on file',
    },
  ]

  return NextResponse.json({ data })
}
