import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'mio_001',
      tenantName: 'Rachel Green',
      tenantEmail: 'rachel.green@email.com',
      property: 'Sunset Towers',
      unit: 'Unit 5B',
      type: 'move_in',
      scheduledDate: '2026-03-15T09:00:00Z',
      completedDate: null,
      status: 'scheduled',
      checklistProgress: 60,
      checklistTotal: 10,
      checklistCompleted: 6,
      depositAmount: 2500.0,
      depositStatus: 'collected',
      notes: 'Elevator reserved for move-in 9AM–12PM. Parking spot #47 assigned.',
    },
    {
      id: 'mio_002',
      tenantName: 'Tom Bradley',
      tenantEmail: 'tom.bradley@email.com',
      property: 'Maple Grove Residences',
      unit: 'Unit 9A',
      type: 'move_out',
      scheduledDate: '2026-03-10T10:00:00Z',
      completedDate: null,
      status: 'in_progress',
      checklistProgress: 75,
      checklistTotal: 12,
      checklistCompleted: 9,
      depositAmount: 2000.0,
      depositStatus: 'pending_review',
      notes: 'Move-out inspection scheduled for March 12. Minor wall repair needed.',
    },
    {
      id: 'mio_003',
      tenantName: 'Priya Sharma',
      tenantEmail: 'priya.sharma@email.com',
      property: 'Harbor View Apartments',
      unit: 'Unit 14C',
      type: 'move_in',
      scheduledDate: '2026-03-20T08:00:00Z',
      completedDate: null,
      status: 'scheduled',
      checklistProgress: 30,
      checklistTotal: 10,
      checklistCompleted: 3,
      depositAmount: 3000.0,
      depositStatus: 'pending',
      notes: 'Pet deposit additional $500. Key fob #HVA-1142 assigned.',
    },
    {
      id: 'mio_004',
      tenantName: 'Marcus Johnson',
      tenantEmail: 'marcus.j@email.com',
      property: 'Oakwood Estates',
      unit: 'Unit 2D',
      type: 'move_out',
      scheduledDate: '2026-02-28T10:00:00Z',
      completedDate: '2026-02-28T16:30:00Z',
      status: 'completed',
      checklistProgress: 100,
      checklistTotal: 12,
      checklistCompleted: 12,
      depositAmount: 2200.0,
      depositStatus: 'refunded',
      notes: 'Full deposit refunded. Unit cleaned and ready for showing.',
    },
    {
      id: 'mio_005',
      tenantName: 'Sophie Laurent',
      tenantEmail: 'sophie.l@email.com',
      property: 'Riverside Lofts',
      unit: 'Unit 11A',
      type: 'move_in',
      scheduledDate: '2026-04-01T09:00:00Z',
      completedDate: null,
      status: 'approved',
      checklistProgress: 10,
      checklistTotal: 10,
      checklistCompleted: 1,
      depositAmount: 2750.0,
      depositStatus: 'collected',
      notes: 'Lease signed electronically. Welcome package prepared.',
    },
    {
      id: 'mio_006',
      tenantName: 'Carlos Mendez',
      tenantEmail: 'carlos.m@email.com',
      property: 'Cedar Park Villas',
      unit: 'Unit 6B',
      type: 'move_out',
      scheduledDate: '2026-03-05T10:00:00Z',
      completedDate: null,
      status: 'in_progress',
      checklistProgress: 50,
      checklistTotal: 12,
      checklistCompleted: 6,
      depositAmount: 1800.0,
      depositStatus: 'pending_review',
      notes: 'Carpet replacement likely needed. Final walkthrough on March 7.',
    },
  ]

  return NextResponse.json({ data })
}
