import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'bgt_001',
      name: 'Building Maintenance',
      category: 'maintenance',
      property: 'Sunset Towers',
      allocatedAmount: 85000,
      spentAmount: 62300,
      remainingAmount: 22700,
      period: '2026',
      quarter: 'Q1',
      variance: -3.8,
      status: 'on_track',
      lastUpdated: '2026-03-01T00:00:00Z',
      description: 'General building maintenance including HVAC, plumbing, and electrical repairs.',
    },
    {
      id: 'bgt_002',
      name: 'Capital Improvements',
      category: 'capital',
      property: 'Portfolio Wide',
      allocatedAmount: 150000,
      spentAmount: 112500,
      remainingAmount: 37500,
      period: '2026',
      quarter: 'Q1',
      variance: +2.1,
      status: 'on_track',
      lastUpdated: '2026-03-01T00:00:00Z',
      description: 'Major capital improvement projects including roof replacement and lobby renovation.',
    },
    {
      id: 'bgt_003',
      name: 'Insurance Premiums',
      category: 'operating',
      property: 'Portfolio Wide',
      allocatedAmount: 62000,
      spentAmount: 62000,
      remainingAmount: 0,
      period: '2026',
      quarter: 'Q1',
      variance: 0,
      status: 'fully_spent',
      lastUpdated: '2026-02-15T00:00:00Z',
      description: 'Annual property insurance premiums paid in full at policy renewal.',
    },
    {
      id: 'bgt_004',
      name: 'Landscaping & Grounds',
      category: 'maintenance',
      property: 'Maple Grove Residences',
      allocatedAmount: 42000,
      spentAmount: 38900,
      remainingAmount: 3100,
      period: '2026',
      quarter: 'Q1',
      variance: -12.4,
      status: 'over_budget',
      lastUpdated: '2026-03-01T00:00:00Z',
      description: 'Landscaping, lawn care, tree trimming, and seasonal planting.',
    },
    {
      id: 'bgt_005',
      name: 'Marketing & Leasing',
      category: 'operating',
      property: 'Portfolio Wide',
      allocatedAmount: 35000,
      spentAmount: 18400,
      remainingAmount: 16600,
      period: '2026',
      quarter: 'Q1',
      variance: +5.2,
      status: 'under_budget',
      lastUpdated: '2026-03-01T00:00:00Z',
      description: 'Online listings, virtual tours, signage, and leasing agent commissions.',
    },
    {
      id: 'bgt_006',
      name: 'Technology & Software',
      category: 'operating',
      property: 'Portfolio Wide',
      allocatedAmount: 28000,
      spentAmount: 21500,
      remainingAmount: 6500,
      period: '2026',
      quarter: 'Q1',
      variance: -1.0,
      status: 'on_track',
      lastUpdated: '2026-03-01T00:00:00Z',
      description: 'Property management software, smart home systems, and IT infrastructure.',
    },
  ]

  return NextResponse.json({ data })
}
