import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'dsp_001',
      title: 'Excessive Noise After Quiet Hours',
      type: 'noise',
      priority: 'high',
      reportedBy: 'Rachel Green',
      reportedByUnit: 'Unit 5B',
      property: 'Sunset Towers',
      againstTenant: 'Unit 5C — Unidentified guests',
      status: 'open',
      createdAt: '2026-03-02T22:30:00Z',
      updatedAt: '2026-03-03T09:00:00Z',
      resolution: null,
      description: 'Loud music and gatherings after 10 PM on weekdays. Multiple complaints from adjacent units.',
      assignedTo: 'Property Manager — Diana Wells',
    },
    {
      id: 'dsp_002',
      title: 'Water Damage from Upstairs Unit',
      type: 'damage',
      priority: 'critical',
      reportedBy: 'David Kim',
      reportedByUnit: 'Unit 10B',
      property: 'Oakwood Estates',
      againstTenant: 'Unit 11B — Tom Harris',
      status: 'under_review',
      createdAt: '2026-02-28T08:00:00Z',
      updatedAt: '2026-03-02T14:00:00Z',
      resolution: null,
      description: 'Ceiling water damage caused by overflowing bathtub in upstairs unit. Insurance claim initiated.',
      assignedTo: 'Maintenance Lead — Roberto Vega',
    },
    {
      id: 'dsp_003',
      title: 'Late Rent Payment Dispute',
      type: 'payment',
      priority: 'medium',
      reportedBy: 'Property Management',
      reportedByUnit: 'Leasing Office',
      property: 'Maple Grove Residences',
      againstTenant: 'Unit 9A — Tom Bradley',
      status: 'open',
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
      resolution: null,
      description: 'Tenant disputes late fee charges. Claims payment was made on time via online portal but was not processed.',
      assignedTo: 'Property Manager — Diana Wells',
    },
    {
      id: 'dsp_004',
      title: 'Unauthorized Parking Space Usage',
      type: 'common_area',
      priority: 'low',
      reportedBy: 'Anna Williams',
      reportedByUnit: 'Unit 6B',
      property: 'Riverside Lofts',
      againstTenant: 'Unknown vehicle — License 7ABC123',
      status: 'open',
      createdAt: '2026-03-03T07:30:00Z',
      updatedAt: '2026-03-03T07:30:00Z',
      resolution: null,
      description: 'Assigned parking spot #31 occupied by unauthorized vehicle. Third occurrence this month.',
      assignedTo: 'Front Desk — Security Team',
    },
    {
      id: 'dsp_005',
      title: 'Lease Terms Misinterpretation',
      type: 'lease',
      priority: 'medium',
      reportedBy: 'Carlos Mendez',
      reportedByUnit: 'Unit 6B',
      property: 'Cedar Park Villas',
      againstTenant: 'Property Management',
      status: 'under_review',
      createdAt: '2026-02-20T10:00:00Z',
      updatedAt: '2026-02-28T16:00:00Z',
      resolution: null,
      description: 'Tenant claims lease terms regarding early termination were misrepresented. Legal review requested.',
      assignedTo: 'Legal Counsel — Morrison & Associates',
    },
    {
      id: 'dsp_006',
      title: 'Pet-Related Property Damage',
      type: 'damage',
      priority: 'medium',
      reportedBy: 'Property Management',
      reportedByUnit: 'Maintenance Office',
      property: 'Sunset Towers',
      againstTenant: 'Unit 8A — James Cooper',
      status: 'resolved',
      createdAt: '2026-02-10T09:00:00Z',
      updatedAt: '2026-02-25T11:00:00Z',
      resolution: 'Tenant agreed to pay $450 for carpet repair. Amount deducted from pet deposit.',
      description: 'Scratch damage to hallway carpet caused by tenant dog. Photo evidence documented.',
      assignedTo: 'Property Manager — Diana Wells',
    },
  ]

  return NextResponse.json({ data })
}
