import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'esig_001',
      documentName: 'Residential Lease Agreement — Unit 5B',
      documentType: 'lease',
      requestedBy: 'Property Management',
      requestedFrom: 'Rachel Green',
      requestedFromEmail: 'rachel.green@email.com',
      status: 'pending_signature',
      createdAt: '2026-03-01T10:00:00Z',
      expiresAt: '2026-03-15T23:59:59Z',
      signedAt: null,
      property: 'Sunset Towers',
      unit: 'Unit 5B',
      parties: ['TenantFlow Management LLC', 'Rachel Green'],
      priority: 'high',
    },
    {
      id: 'esig_002',
      documentName: 'Lease Renewal — Unit 9A',
      documentType: 'renewal',
      requestedBy: 'Property Management',
      requestedFrom: 'Tom Bradley',
      requestedFromEmail: 'tom.bradley@email.com',
      status: 'completed',
      createdAt: '2026-02-15T09:00:00Z',
      expiresAt: '2026-02-28T23:59:59Z',
      signedAt: '2026-02-18T14:32:00Z',
      property: 'Maple Grove Residences',
      unit: 'Unit 9A',
      parties: ['TenantFlow Management LLC', 'Tom Bradley'],
      priority: 'medium',
    },
    {
      id: 'esig_003',
      documentName: 'Pet Addendum — Unit 14C',
      documentType: 'addendum',
      requestedBy: 'Property Management',
      requestedFrom: 'Priya Sharma',
      requestedFromEmail: 'priya.sharma@email.com',
      status: 'pending_signature',
      createdAt: '2026-03-02T11:30:00Z',
      expiresAt: '2026-03-16T23:59:59Z',
      signedAt: null,
      property: 'Harbor View Apartments',
      unit: 'Unit 14C',
      parties: ['TenantFlow Management LLC', 'Priya Sharma'],
      priority: 'medium',
    },
    {
      id: 'esig_004',
      documentName: 'Move-Out Settlement Statement',
      documentType: 'settlement',
      requestedBy: 'Property Management',
      requestedFrom: 'Marcus Johnson',
      requestedFromEmail: 'marcus.j@email.com',
      status: 'completed',
      createdAt: '2026-02-28T16:00:00Z',
      expiresAt: '2026-03-14T23:59:59Z',
      signedAt: '2026-02-28T17:15:00Z',
      property: 'Oakwood Estates',
      unit: 'Unit 2D',
      parties: ['TenantFlow Management LLC', 'Marcus Johnson'],
      priority: 'high',
    },
    {
      id: 'esig_005',
      documentName: 'Parking Space Assignment — Unit 11A',
      documentType: 'addendum',
      requestedBy: 'Property Management',
      requestedFrom: 'Sophie Laurent',
      requestedFromEmail: 'sophie.l@email.com',
      status: 'pending_review',
      createdAt: '2026-03-03T08:00:00Z',
      expiresAt: '2026-03-17T23:59:59Z',
      signedAt: null,
      property: 'Riverside Lofts',
      unit: 'Unit 11A',
      parties: ['TenantFlow Management LLC', 'Sophie Laurent'],
      priority: 'low',
    },
    {
      id: 'esig_006',
      documentName: 'Lease Termination Agreement — Unit 6B',
      documentType: 'termination',
      requestedBy: 'Carlos Mendez',
      requestedFrom: 'Property Management',
      requestedFromEmail: 'admin@apexflow.cloud',
      status: 'pending_signature',
      createdAt: '2026-03-03T12:00:00Z',
      expiresAt: '2026-03-10T23:59:59Z',
      signedAt: null,
      property: 'Cedar Park Villas',
      unit: 'Unit 6B',
      parties: ['TenantFlow Management LLC', 'Carlos Mendez'],
      priority: 'high',
    },
  ]

  return NextResponse.json({ data })
}
