import { NextResponse } from 'next/server'

export async function GET() {
  const data = [
    {
      id: 'er_001',
      property: 'Sunset Towers',
      unitName: 'Unit 4A',
      type: 'electric',
      consumption: 1245.6,
      unitOfMeasure: 'kWh',
      cost: 186.84,
      rate: 0.15,
      period: '2026-02',
      timestamp: '2026-02-28T23:59:00Z',
      status: 'active',
      trend: +3.2,
      carbonOffset: 0.62,
      provider: 'Pacific Gas & Electric',
    },
    {
      id: 'er_002',
      property: 'Maple Grove Residences',
      unitName: 'Unit 12B',
      type: 'gas',
      consumption: 845.3,
      unitOfMeasure: 'therms',
      cost: 676.24,
      rate: 0.80,
      period: '2026-02',
      timestamp: '2026-02-28T23:59:00Z',
      status: 'warning',
      trend: +12.5,
      carbonOffset: 4.82,
      provider: 'Southern California Gas',
    },
    {
      id: 'er_003',
      property: 'Harbor View Apartments',
      unitName: 'Common Areas',
      type: 'water',
      consumption: 38200,
      unitOfMeasure: 'gallons',
      cost: 152.80,
      rate: 0.004,
      period: '2026-02',
      timestamp: '2026-02-28T23:59:00Z',
      status: 'active',
      trend: -5.1,
      carbonOffset: 0,
      provider: 'City Water District',
    },
    {
      id: 'er_004',
      property: 'Oakwood Estates',
      unitName: 'Rooftop Array',
      type: 'solar',
      consumption: 2100.0,
      unitOfMeasure: 'kWh',
      cost: -315.00,
      rate: 0.15,
      period: '2026-02',
      timestamp: '2026-02-28T23:59:00Z',
      status: 'active',
      trend: +8.7,
      carbonOffset: 1.05,
      provider: 'SunPower Solar',
    },
    {
      id: 'er_005',
      property: 'Riverside Lofts',
      unitName: 'Unit 7C',
      type: 'electric',
      consumption: 987.4,
      unitOfMeasure: 'kWh',
      cost: 148.11,
      rate: 0.15,
      period: '2026-02',
      timestamp: '2026-02-28T23:59:00Z',
      status: 'critical',
      trend: +22.8,
      carbonOffset: 0.49,
      provider: 'Pacific Gas & Electric',
    },
    {
      id: 'er_006',
      property: 'Cedar Park Villas',
      unitName: 'Common Areas',
      type: 'gas',
      consumption: 620.8,
      unitOfMeasure: 'therms',
      cost: 496.64,
      rate: 0.80,
      period: '2026-02',
      timestamp: '2026-02-28T23:59:00Z',
      status: 'active',
      trend: -2.3,
      carbonOffset: 3.54,
      provider: 'Cascade Natural Gas',
    },
  ]

  return NextResponse.json({ data })
}
